// <auto-generated />
namespace calx.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class makepricedoubleaftermistak : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(makepricedoubleaftermistak));
        
        string IMigrationMetadata.Id
        {
            get { return "202304160556112_make-price-double-after-mistak"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
